#!/bin/bash
# Combined Security Hardening Script
# Run with: sudo ./scripts/apply-security-hardening.sh
#
# This script:
#   1. Installs and configures UFW firewall
#   2. Applies SSH hardening (key-only, no root)
#
# IMPORTANT: Make sure you have SSH key access before running!

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root: sudo $0${NC}"
    exit 1
fi

echo ""
echo -e "${YELLOW}🔒 Security Hardening Script${NC}"
echo "=============================="
echo ""
echo "This script will:"
echo "  1. Install & configure UFW firewall"
echo "  2. Harden SSH (disable password auth, disable root login)"
echo ""
echo -e "${YELLOW}⚠️  WARNING: Ensure you have SSH key access before continuing!${NC}"
echo ""
read -p "Continue? (yes/no) " -r
if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
    echo "Aborting."
    exit 1
fi

# =============================
# Part 1: UFW Firewall
# =============================
echo ""
echo -e "${GREEN}🔥 Installing UFW firewall...${NC}"
apt-get update
apt-get install -y ufw

# Default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH (critical!)
ufw allow ssh

# Allow common ports for home server
ufw allow 80/tcp    # HTTP
ufw allow 443/tcp   # HTTPS
ufw allow 53/tcp    # DNS (AdGuard)
ufw allow 53/udp    # DNS (AdGuard)

# Docker ports (if accessing directly)
# ufw allow 8080/tcp  # Traefik dashboard
# ufw allow 3000/tcp  # API

# Enable firewall
echo "y" | ufw enable
ufw status verbose

echo -e "${GREEN}✓ UFW firewall configured${NC}"

# =============================
# Part 2: SSH Hardening
# =============================
echo ""
echo -e "${GREEN}🔒 Hardening SSH configuration...${NC}"

# Backup original config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d%H%M%S)

# Create hardened SSH config
cat > /etc/ssh/sshd_config.d/99-hardening.conf << 'EOF'
# SSH Hardening Configuration
# Generated by apply-security-hardening.sh

# Disable password authentication (key only)
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes

# Disable root login
PermitRootLogin no

# Allow only specific authentication methods
AuthenticationMethods publickey
PubkeyAuthentication yes

# Stricter settings
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 30

# Disable unnecessary features
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no

# Logging
LogLevel VERBOSE
EOF

# Test config
echo "Testing SSH configuration..."
if sshd -t; then
    echo -e "${GREEN}✓ Configuration valid${NC}"
else
    echo -e "${RED}✗ Configuration error, reverting...${NC}"
    rm /etc/ssh/sshd_config.d/99-hardening.conf
    exit 1
fi

# Restart SSH
systemctl restart sshd

echo ""
echo "============================================"
echo -e "${GREEN}✅ Security hardening complete!${NC}"
echo "============================================"
echo ""
echo "Changes made:"
echo ""
echo "UFW Firewall:"
echo "  - Default: deny incoming, allow outgoing"
echo "  - Allowed: SSH, HTTP (80), HTTPS (443), DNS (53)"
echo ""
echo "SSH Hardening:"
echo "  - Password authentication: DISABLED"
echo "  - Root login: DISABLED"
echo "  - Max auth tries: 3"
echo "  - X11/Agent/TCP forwarding: DISABLED"
echo ""
echo "Backup saved to: /etc/ssh/sshd_config.backup.*"
echo ""
echo -e "${YELLOW}⚠️  Test your SSH connection in a new terminal before closing this one!${NC}"
echo ""
