#!/bin/bash
# SSH Hardening Script
# 
# Usage: sudo ./harden-ssh.sh
#
# This script:
#   1. Disables password authentication (SSH key only)
#   2. Disables root login
#   3. Sets stricter SSH settings
#
# IMPORTANT: Make sure you have SSH key access before running!

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Please run as root: sudo $0${NC}"
    exit 1
fi

echo -e "${YELLOW}⚠️  WARNING: This will disable SSH password authentication!${NC}"
echo ""
echo "Before continuing, ensure you have:"
echo "  1. SSH key access to this server"
echo "  2. Tested that 'ssh home-server' works with your key"
echo ""
read -p "Have you verified SSH key access? (yes/no) " -r
if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
    echo "Aborting. Set up SSH keys first:"
    echo "  ssh-copy-id user@server"
    exit 1
fi

echo ""
echo -e "${GREEN}🔒 Hardening SSH configuration...${NC}"

# Backup original config
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)

# Create hardened SSH config
cat > /etc/ssh/sshd_config.d/99-hardening.conf << 'EOF'
# SSH Hardening Configuration
# Generated by harden-ssh.sh

# Disable password authentication (key only)
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM yes

# Disable root login
PermitRootLogin no

# Allow only specific authentication methods
AuthenticationMethods publickey
PubkeyAuthentication yes

# Stricter settings
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 30

# Disable unnecessary features
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no

# Use only secure algorithms (optional, uncomment for extra security)
# KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group16-sha512
# Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com
# MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com

# Logging
LogLevel VERBOSE
EOF

# Test config
echo "Testing SSH configuration..."
if sshd -t; then
    echo -e "${GREEN}✓ Configuration valid${NC}"
else
    echo -e "${RED}✗ Configuration error, reverting...${NC}"
    rm /etc/ssh/sshd_config.d/99-hardening.conf
    exit 1
fi

# Restart SSH
systemctl restart sshd

echo ""
echo -e "${GREEN}✅ SSH hardening complete!${NC}"
echo ""
echo "Changes made:"
echo "  - Password authentication: DISABLED"
echo "  - Root login: DISABLED"
echo "  - Max auth tries: 3"
echo "  - X11/Agent/TCP forwarding: DISABLED"
echo ""
echo "Backup saved to: /etc/ssh/sshd_config.backup.*"
echo ""
echo -e "${YELLOW}Test your SSH connection in a new terminal before closing this one!${NC}"
