- resources:
    cpu: true
    memory: true
    disk:
      - /
      - /data
    expanded: true
- docker:
    expanded: false
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
